name: 'stkbot'

on:
  workflow_dispatch:
  schedule:
    - cron: '25 2/4 * * *'


jobs:
  stk-start:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: 'Install requirements'
        run: pip install -r ./requirements.txt
      - name: 'Working'
        env:
          PUSHDEER: ${{ secrets.PUSHDEER }}
          SSYCYX: ${{ secrets.SSYCYX }}
          CPS: ${{ secrets.CPS_ID }}
          SERVERCHAN: ${{ secrets.SERVERCHAN }}
        run: python ./main.py
